name: Run TS tests
on:
  - push
  - pull_request
jobs:
  test-ts:
    name: 'jsbt v0.4.5' # Should match commit below
    uses: paulmillr/jsbt/.github/workflows/test-js-matrix.yml@8a0e8bacab177cbe72ee412345d42331cfc0a261
